### ISSUE TITLE
Bug: Resolve discrepancy in Accumulative Swing Index

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-strategy-py#2]
The output of ASI does not match that from the node lib (which uses `BigN`). There must be a bug somewhere, either in the python or the node implementation, although they appear to match perfectly.

Investigate.

re https://github.com/bitfinexcom/bfx-hf-indicators/blob/master/lib/accumulative_swing_index.js

**Comment by quadramadery** [comment]
hi,
problem is in JS library with how `r` is calculated.
js: `const r = tr.minus((er.times(0.5)).plus(sh.times(0.25)))`
py: `r = tr - (er * 0.5) + (sh * 0.25)`

if you look closer at parentheses in js expression you'll notice that js version actually does `tr - (er*0.5 + sh*0.25)`
