### ISSUE TITLE
Bitfinex api websocket 2 doesn't send 'oc' message  

### ISSUE THREAD

**Issue by soma75** [bitfinexcom/bfx-hf-strategy-py#5]
I use bitfinex websocket v2 . When I send a cancel order, I do receive notification 

[0, 'n', [1540729329489, 'oc-req', ..., 'SUCCESS', 'Submitted for cancellation; waiting for confirmation (ID: xxx).']]] 

But I never received the 'oc' message, it seems bitfinex websocket doen't send anymore 'oc' to confirm the new order's status (wihch is cancelled).

Please can you tell if you face the same issue ?

Thank you in advance

**Comment by f3rno** [comment]
@soma75 are you using sequence auditing (is `seqAudit` set to true in the constructor)?

**Comment by soma75** [comment]
Hi f3rno,
I'm using python, my code used to work, I was receiving 'oc' message but since few days this message is not sent any more (I have changed nothing in my code). Do you face the same issue ?

**Comment by f3rno** [comment]
Hmm, what library are you using to connect to our API? We haven't changed anything on our end.

**Comment by soma75** [comment]
import asyncio
import websockets

**Comment by f3rno** [comment]
Are you using two different sockets, one to cancel the order and another to listen for the `oc` packet? This is very strange, I cannot reproduce, everything looks fine on our end. I recommend you use the `btfxwss` library for interfacing with our API.

**Comment by soma75** [comment]
which payload do you use to cancel one order ?

I use this one 
// Cancel order using client order Id and order creation date
[
  0,
  "oc",
  null,
  {
    "cid": CID,
    "cid_date": CID_DATE
  }
]

Do you use this payload ?
// Cancel order by internal order Id
[
  0,
  "oc",
  null,
  {
    "id": ID
  }
]

**Comment by f3rno** [comment]
Yes, those are correct. How are you listening for events on the API? It looks like you are rolling your own API wrapper, and not using any prebuilt library for the task, so it's likely the bug is on your end.

**Comment by soma75** [comment]
I found my mistake. In the payload it was

PAYLOAD = {
      'apiKey': API_KEY,
      'event': 'auth',
      'authPayload': auth_payload,
      'authNonce': nonce,
      'authSig': signature,
      'filter': ['wallet']
    }

I forgot to add 'trading' in 'filter'

PAYLOAD = {
      'apiKey': API_KEY,
      'event': 'auth',
      'authPayload': auth_payload,
      'authNonce': nonce,
      'authSig': signature,
      'filter': ['wallet', 'trading-'+symbol]
    }

Now I receive the 'oc' message.

Thank you so much for your help

**Comment by f3rno** [comment]
No problem, I'm glad you sorted it out :)
